version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile.php
    ports:
      - "8080:80"
    depends_on:
      - mysql

  mysql:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    environment:
      MYSQL_DATABASE: food_db
      MYSQL_USER: root
      MYSQL_PASSWORD: ""
    ports:
      - "3306:3306"
